#!/usr/bin/env zsh

# Get the directory of this file (zshrc) and env, setup, aliases and functions.
ZSH_CONFIG_DIR=`dirname $(readlink $HOME/.zshrc)`

# Exports. This could be sourced by placing the file in $HOME/.zshenv,
# but not on OSX!
source $ZSH_CONFIG_DIR/env
# zsh settings.
source $ZSH_CONFIG_DIR/setup
# Aliases.
source $ZSH_CONFIG_DIR/aliases
# Functions.
source $ZSH_CONFIG_DIR/functions

# Allow direnv.
eval "$(direnv hook zsh)"

# Python pyenv initializer.
eval "$(pyenv init -)"

# asdf
source /usr/local/opt/asdf/asdf.sh
